os:
  - linux
  - osx
language: r
r:
  - oldrel
  - release
  - devel
cache: packages
r_binary_packages:
  - R6
  - randomForest
  - party
  - gbm
  - lme4
  - glmmML
  - nlme
  - tree
  - rpart
  - mgcv
  - gam
  - ranger
  - MASS
  - MCMCglmm
repos:
  CRAN: https://cloud.r-project.org
  glmmadmb: http://glmmadmb.r-forge.r-project.org/repos
before_script:
  - rm .travis.yml
  - R -e 'install.packages("roxygen2");devtools::document()'
sudo:
  required
