os:
  - linux
  - osx
language: r
r:
  - oldrel
  - release
  - devel
# Tentative, until Travis-CI can test devel on osx.
exclude:
    - r: devel
      os: osx
cache: packages
repos:
  CRAN: https://cloud.r-project.org
before_install:
  - R -e 'install.packages("devtools")'
  - R -e 'install.packages("R2admb")'
  - R -e 'install.packages("glmmADMB", repos=c("http://glmmadmb.r-forge.r-project.org/repos", getOption("repos")), type="source")'
# Tentative.
before_install:
  - R -e 'install.packages("tree", repos = "https://mran.microsoft.com/snapshot/2019-04-15")'
before_script:
  - rm .travis.yml
  - rm install.sh
  - rm include.r
  - R -e 'install.packages("roxygen2")'
  - R -e 'devtools::document()'
