language: r
cache: packages
r_binary_packages:
  - R6
  - randomForest
  - party
  - gbm
  - e1071
  - lme4
  - glmmML
  - nlme
  - tree
  - rpart
  - mgcv
  - gam
  - ranger
  - MASS
repos:
  CRAN: https://cloud.r-project.org
  glmmadmb: http://glmmadmb.r-forge.r-project.org/repos
before_script:
  rm .travis.yml
sudo:
  true
